#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: actuator-demo
server:
  port: 8030

spring:
  application:
    name: prometheus-demo
